json.id @post.id
json.pulocation @post.pulocation
json.packagetype @post.packagetype
json.earlyputime @post.earlyputime
json.lateputime @post.lateputime
json.destination @post.destination
json.earlydelitime @post.earlydelitime
json.latedelitime @post.latedelitime
json.remarks @post.remarks
json.user_id @post.user_id
json.status @post.status
json.postman_id @post.postman_id